app = "leilabot"
primary_region = "syd"

[build]
  # Dockerfile is used automatically

[env]
  # non-secret env vars (leave empty)

[processes]
  app = "python bot.py"

[vm]
  size = "shared-cpu-1x"
  memory = "256mb"
