app = "leilabot"
primary_region = "syd"

[build]
  # Dockerfile used by default

[env]
  # no non-secret env vars here

[processes]
  app = "python bot.py"

[vm]
  size = "shared-cpu-1x"
  memory = "256mb"
